import { type Champion, Lane } from "../types";

export const CHAMPIONS: Record<string, Champion> = {
	aatrox: { key: "aatrox", name: "Aatrox", primaryLane: Lane.Top },
	ahri: { key: "ahri", name: "Ahri", primaryLane: Lane.Mid },
	akali: {
		key: "akali",
		name: "Akali",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	akshan: {
		key: "akshan",
		name: "Akshan",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	alistar: { key: "alistar", name: "Alistar", primaryLane: Lane.Support },
	ambessa: {
		key: "ambessa",
		name: "Ambessa",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	amumu: {
		key: "amumu",
		name: "Amumu",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Support,
	},
	anivia: { key: "anivia", name: "Anivia", primaryLane: Lane.Mid },
	annie: {
		key: "annie",
		name: "Annie",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	aphelios: { key: "aphelios", name: "Aphelios", primaryLane: Lane.ADC },
	ashe: {
		key: "ashe",
		name: "Ashe",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Support,
	},
	aurelionSol: {
		key: "aurelionSol",
		name: "Aurelion Sol",
		primaryLane: Lane.Mid,
	},
	aurora: {
		key: "aurora",
		name: "Aurora",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	azir: { key: "azir", name: "Azir", primaryLane: Lane.Mid },
	bard: { key: "bard", name: "Bard", primaryLane: Lane.Support },
	belveth: { key: "belveth", name: "Bel'Veth", primaryLane: Lane.Jungle },
	blitzcrank: {
		key: "blitzcrank",
		name: "Blitzcrank",
		primaryLane: Lane.Support,
	},
	brand: {
		key: "brand",
		name: "Brand",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	braum: { key: "braum", name: "Braum", primaryLane: Lane.Support },
	briar: {
		key: "briar",
		name: "Briar",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	caitlyn: { key: "caitlyn", name: "Caitlyn", primaryLane: Lane.ADC },
	camille: { key: "camille", name: "Camille", primaryLane: Lane.Top },
	cassiopeia: {
		key: "cassiopeia",
		name: "Cassiopeia",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	chogath: {
		key: "chogath",
		name: "Cho'Gath",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	corki: {
		key: "corki",
		name: "Corki",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.ADC,
	},
	darius: { key: "darius", name: "Darius", primaryLane: Lane.Top },
	diana: {
		key: "diana",
		name: "Diana",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	drMundo: {
		key: "drMundo",
		name: "Dr. Mundo",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	draven: { key: "draven", name: "Draven", primaryLane: Lane.ADC },
	ekko: {
		key: "ekko",
		name: "Ekko",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	elise: { key: "elise", name: "Elise", primaryLane: Lane.Jungle },
	evelynn: { key: "evelynn", name: "Evelynn", primaryLane: Lane.Jungle },
	ezreal: { key: "ezreal", name: "Ezreal", primaryLane: Lane.ADC },
	fiddlesticks: {
		key: "fiddlesticks",
		name: "Fiddlesticks",
		primaryLane: Lane.Jungle,
	},
	fiora: { key: "fiora", name: "Fiora", primaryLane: Lane.Top },
	fizz: { key: "fizz", name: "Fizz", primaryLane: Lane.Mid },
	galio: {
		key: "galio",
		name: "Galio",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	gangplank: { key: "gangplank", name: "Gangplank", primaryLane: Lane.Top },
	garen: { key: "garen", name: "Garen", primaryLane: Lane.Top },
	gnar: { key: "gnar", name: "Gnar", primaryLane: Lane.Top },
	gragas: {
		key: "gragas",
		name: "Gragas",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	graves: { key: "graves", name: "Graves", primaryLane: Lane.Jungle },
	gwen: {
		key: "gwen",
		name: "Gwen",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	hecarim: { key: "hecarim", name: "Hecarim", primaryLane: Lane.Jungle },
	heimerdinger: {
		key: "heimerdinger",
		name: "Heimerdinger",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	hwei: {
		key: "hwei",
		name: "Hwei",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	illaoi: { key: "illaoi", name: "Illaoi", primaryLane: Lane.Top },
	irelia: {
		key: "irelia",
		name: "Irelia",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	ivern: {
		key: "ivern",
		name: "Ivern",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Support,
	},
	janna: { key: "janna", name: "Janna", primaryLane: Lane.Support },
	jarvanIV: { key: "jarvanIV", name: "Jarvan IV", primaryLane: Lane.Jungle },
	jax: {
		key: "jax",
		name: "Jax",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	jayce: {
		key: "jayce",
		name: "Jayce",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	jhin: { key: "jhin", name: "Jhin", primaryLane: Lane.ADC },
	jinx: { key: "jinx", name: "Jinx", primaryLane: Lane.ADC },
	ksante: { key: "ksante", name: "K'Sante", primaryLane: Lane.Top },
	kaisa: { key: "kaisa", name: "Kai'Sa", primaryLane: Lane.ADC },
	kalista: { key: "kalista", name: "Kalista", primaryLane: Lane.ADC },
	karma: {
		key: "karma",
		name: "Karma",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	karthus: {
		key: "karthus",
		name: "Karthus",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	kassadin: { key: "kassadin", name: "Kassadin", primaryLane: Lane.Mid },
	katarina: { key: "katarina", name: "Katarina", primaryLane: Lane.Mid },
	kayle: {
		key: "kayle",
		name: "Kayle",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	kayn: { key: "kayn", name: "Kayn", primaryLane: Lane.Jungle },
	kennen: {
		key: "kennen",
		name: "Kennen",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	khazix: { key: "khazix", name: "Kha'Zix", primaryLane: Lane.Jungle },
	kindred: { key: "kindred", name: "Kindred", primaryLane: Lane.Jungle },
	kled: { key: "kled", name: "Kled", primaryLane: Lane.Top },
	kogmaw: { key: "kogmaw", name: "Kog'Maw", primaryLane: Lane.ADC },
	leblanc: { key: "leblanc", name: "LeBlanc", primaryLane: Lane.Mid },
	leeSin: { key: "leeSin", name: "Lee Sin", primaryLane: Lane.Jungle },
	leona: { key: "leona", name: "Leona", primaryLane: Lane.Support },
	lillia: {
		key: "lillia",
		name: "Lillia",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	lissandra: { key: "lissandra", name: "Lissandra", primaryLane: Lane.Mid },
	lucian: {
		key: "lucian",
		name: "Lucian",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	lulu: { key: "lulu", name: "Lulu", primaryLane: Lane.Support },
	lux: {
		key: "lux",
		name: "Lux",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	malphite: {
		key: "malphite",
		name: "Malphite",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	malzahar: { key: "malzahar", name: "Malzahar", primaryLane: Lane.Mid },
	maokai: {
		key: "maokai",
		name: "Maokai",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Jungle,
	},
	masterYi: { key: "masterYi", name: "Master Yi", primaryLane: Lane.Jungle },
	mel: {
		key: "mel",
		name: "Mel",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	milio: { key: "milio", name: "Milio", primaryLane: Lane.Support },
	missFortune: {
		key: "missFortune",
		name: "Miss Fortune",
		primaryLane: Lane.ADC,
	},
	mordekaiser: {
		key: "mordekaiser",
		name: "Mordekaiser",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	morgana: {
		key: "morgana",
		name: "Morgana",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Jungle,
	},
	naafiri: {
		key: "naafiri",
		name: "Naafiri",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	nami: { key: "nami", name: "Nami", primaryLane: Lane.Support },
	nasus: { key: "nasus", name: "Nasus", primaryLane: Lane.Top },
	nautilus: { key: "nautilus", name: "Nautilus", primaryLane: Lane.Support },
	neeko: {
		key: "neeko",
		name: "Neeko",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	nidalee: { key: "nidalee", name: "Nidalee", primaryLane: Lane.Jungle },
	nilah: { key: "nilah", name: "Nilah", primaryLane: Lane.ADC },
	nocturne: { key: "nocturne", name: "Nocturne", primaryLane: Lane.Jungle },
	nunu: { key: "nunu", name: "Nunu & Willump", primaryLane: Lane.Jungle },
	olaf: {
		key: "olaf",
		name: "Olaf",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	orianna: { key: "orianna", name: "Orianna", primaryLane: Lane.Mid },
	ornn: { key: "ornn", name: "Ornn", primaryLane: Lane.Top },
	pantheon: {
		key: "pantheon",
		name: "Pantheon",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Top,
	},
	poppy: {
		key: "poppy",
		name: "Poppy",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	pyke: {
		key: "pyke",
		name: "Pyke",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	qiyana: {
		key: "qiyana",
		name: "Qiyana",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Jungle,
	},
	quinn: { key: "quinn", name: "Quinn", primaryLane: Lane.Top },
	rakan: { key: "rakan", name: "Rakan", primaryLane: Lane.Support },
	rammus: { key: "rammus", name: "Rammus", primaryLane: Lane.Jungle },
	reksai: { key: "reksai", name: "Rek'Sai", primaryLane: Lane.Jungle },
	rell: { key: "rell", name: "Rell", primaryLane: Lane.Support },
	renataGlasc: {
		key: "renataGlasc",
		name: "Renata Glasc",
		primaryLane: Lane.Support,
	},
	renekton: { key: "renekton", name: "Renekton", primaryLane: Lane.Top },
	rengar: {
		key: "rengar",
		name: "Rengar",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	riven: { key: "riven", name: "Riven", primaryLane: Lane.Top },
	rumble: {
		key: "rumble",
		name: "Rumble",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	ryze: {
		key: "ryze",
		name: "Ryze",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	samira: { key: "samira", name: "Samira", primaryLane: Lane.ADC },
	sejuani: {
		key: "sejuani",
		name: "Sejuani",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	senna: {
		key: "senna",
		name: "Senna",
		primaryLane: Lane.Support,
		secondaryLane: Lane.ADC,
	},
	seraphine: {
		key: "seraphine",
		name: "Seraphine",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	sett: {
		key: "sett",
		name: "Sett",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	shaco: {
		key: "shaco",
		name: "Shaco",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Support,
	},
	shen: {
		key: "shen",
		name: "Shen",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	shyvana: { key: "shyvana", name: "Shyvana", primaryLane: Lane.Jungle },
	singed: { key: "singed", name: "Singed", primaryLane: Lane.Top },
	sion: { key: "sion", name: "Sion", primaryLane: Lane.Top },
	sivir: { key: "sivir", name: "Sivir", primaryLane: Lane.ADC },
	skarner: {
		key: "skarner",
		name: "Skarner",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	smolder: {
		key: "smolder",
		name: "Smolder",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	sona: { key: "sona", name: "Sona", primaryLane: Lane.Support },
	soraka: { key: "soraka", name: "Soraka", primaryLane: Lane.Support },
	swain: {
		key: "swain",
		name: "Swain",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	sylas: {
		key: "sylas",
		name: "Sylas",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	syndra: { key: "syndra", name: "Syndra", primaryLane: Lane.Mid },
	tahmKench: {
		key: "tahmKench",
		name: "Tahm Kench",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	taliyah: {
		key: "taliyah",
		name: "Taliyah",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	talon: {
		key: "talon",
		name: "Talon",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Jungle,
	},
	taric: { key: "taric", name: "Taric", primaryLane: Lane.Support },
	teemo: { key: "teemo", name: "Teemo", primaryLane: Lane.Top },
	thresh: { key: "thresh", name: "Thresh", primaryLane: Lane.Support },
	tristana: {
		key: "tristana",
		name: "Tristana",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	trundle: {
		key: "trundle",
		name: "Trundle",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	tryndamere: { key: "tryndamere", name: "Tryndamere", primaryLane: Lane.Top },
	twistedFate: {
		key: "twistedFate",
		name: "Twisted Fate",
		primaryLane: Lane.Mid,
	},
	twitch: { key: "twitch", name: "Twitch", primaryLane: Lane.ADC },
	udyr: {
		key: "udyr",
		name: "Udyr",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	urgot: { key: "urgot", name: "Urgot", primaryLane: Lane.Top },
	varus: {
		key: "varus",
		name: "Varus",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	vayne: {
		key: "vayne",
		name: "Vayne",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Top,
	},
	veigar: {
		key: "veigar",
		name: "Veigar",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	velkoz: {
		key: "velkoz",
		name: "Vel'Koz",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	vex: { key: "vex", name: "Vex", primaryLane: Lane.Mid },
	vi: { key: "vi", name: "Vi", primaryLane: Lane.Jungle },
	viego: { key: "viego", name: "Viego", primaryLane: Lane.Jungle },
	viktor: { key: "viktor", name: "Viktor", primaryLane: Lane.Mid },
	vladimir: {
		key: "vladimir",
		name: "Vladimir",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	volibear: {
		key: "volibear",
		name: "Volibear",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	warwick: {
		key: "warwick",
		name: "Warwick",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	wukong: {
		key: "wukong",
		name: "Wukong",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	xayah: { key: "xayah", name: "Xayah", primaryLane: Lane.ADC },
	xerath: {
		key: "xerath",
		name: "Xerath",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	xinZhao: { key: "xinZhao", name: "Xin Zhao", primaryLane: Lane.Jungle },
	yasuo: {
		key: "yasuo",
		name: "Yasuo",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	yone: {
		key: "yone",
		name: "Yone",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	yorick: { key: "yorick", name: "Yorick", primaryLane: Lane.Top },
	yunara: { key: "yunara", name: "Yunara", primaryLane: Lane.ADC },
	yuumi: { key: "yuumi", name: "Yuumi", primaryLane: Lane.Support },
	zaahen: { key: "zaahen", name: "Zaahen", primaryLane: Lane.Top },
	zac: {
		key: "zac",
		name: "Zac",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	zed: {
		key: "zed",
		name: "Zed",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Jungle,
	},
	zeri: { key: "zeri", name: "Zeri", primaryLane: Lane.ADC },
	ziggs: {
		key: "ziggs",
		name: "Ziggs",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.ADC,
	},
	zilean: {
		key: "zilean",
		name: "Zilean",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	zoe: { key: "zoe", name: "Zoe", primaryLane: Lane.Mid },
	zyra: {
		key: "zyra",
		name: "Zyra",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
};
