import { type Champion, Lane } from "../types";

export const CHAMPIONS: Record<string, Champion> = {
	Aatrox: { key: "Aatrox", name: "Aatrox", primaryLane: Lane.Top },
	Ahri: { key: "Ahri", name: "Ahri", primaryLane: Lane.Mid },
	Akali: {
		key: "Akali",
		name: "Akali",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	Akshan: {
		key: "Akshan",
		name: "Akshan",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.ADC,
	},
	Alistar: { key: "Alistar", name: "Alistar", primaryLane: Lane.Support },
	Ambessa: { key: "Ambessa", name: "Ambessa", primaryLane: Lane.Top },
	Amumu: {
		key: "Amumu",
		name: "Amumu",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Support,
	},
	Anivia: { key: "Anivia", name: "Anivia", primaryLane: Lane.Mid },
	Annie: {
		key: "Annie",
		name: "Annie",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	Aphelios: { key: "Aphelios", name: "Aphelios", primaryLane: Lane.ADC },
	Ashe: {
		key: "Ashe",
		name: "Ashe",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Support,
	},
	AurelionSol: {
		key: "AurelionSol",
		name: "Aurelion Sol",
		primaryLane: Lane.Mid,
	},
	Aurora: {
		key: "Aurora",
		name: "Aurora",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	Azir: { key: "Azir", name: "Azir", primaryLane: Lane.Mid },
	Bard: { key: "Bard", name: "Bard", primaryLane: Lane.Support },
	Belveth: { key: "Belveth", name: "Bel'Veth", primaryLane: Lane.Jungle },
	Blitzcrank: {
		key: "Blitzcrank",
		name: "Blitzcrank",
		primaryLane: Lane.Support,
	},
	Brand: {
		key: "Brand",
		name: "Brand",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	Braum: { key: "Braum", name: "Braum", primaryLane: Lane.Support },
	Briar: { key: "Briar", name: "Briar", primaryLane: Lane.Jungle },
	Caitlyn: { key: "Caitlyn", name: "Caitlyn", primaryLane: Lane.ADC },
	Camille: { key: "Camille", name: "Camille", primaryLane: Lane.Top },
	Cassiopeia: { key: "Cassiopeia", name: "Cassiopeia", primaryLane: Lane.Mid },
	Chogath: { key: "Chogath", name: "Cho'Gath", primaryLane: Lane.Top },
	Corki: { key: "Corki", name: "Corki", primaryLane: Lane.Mid },
	Darius: { key: "Darius", name: "Darius", primaryLane: Lane.Top },
	Diana: {
		key: "Diana",
		name: "Diana",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	DrMundo: { key: "DrMundo", name: "Dr. Mundo", primaryLane: Lane.Top },
	Draven: { key: "Draven", name: "Draven", primaryLane: Lane.ADC },
	Ekko: {
		key: "Ekko",
		name: "Ekko",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	Elise: { key: "Elise", name: "Elise", primaryLane: Lane.Jungle },
	Evelynn: { key: "Evelynn", name: "Evelynn", primaryLane: Lane.Jungle },
	Ezreal: { key: "Ezreal", name: "Ezreal", primaryLane: Lane.ADC },
	Fiddlesticks: {
		key: "Fiddlesticks",
		name: "Fiddlesticks",
		primaryLane: Lane.Jungle,
	},
	Fiora: { key: "Fiora", name: "Fiora", primaryLane: Lane.Top },
	Fizz: { key: "Fizz", name: "Fizz", primaryLane: Lane.Mid },
	Galio: {
		key: "Galio",
		name: "Galio",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	Gangplank: { key: "Gangplank", name: "Gangplank", primaryLane: Lane.Top },
	Garen: { key: "Garen", name: "Garen", primaryLane: Lane.Top },
	Gnar: { key: "Gnar", name: "Gnar", primaryLane: Lane.Top },
	Gragas: {
		key: "Gragas",
		name: "Gragas",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	Graves: { key: "Graves", name: "Graves", primaryLane: Lane.Jungle },
	Gwen: { key: "Gwen", name: "Gwen", primaryLane: Lane.Top },
	Hecarim: { key: "Hecarim", name: "Hecarim", primaryLane: Lane.Jungle },
	Heimerdinger: {
		key: "Heimerdinger",
		name: "Heimerdinger",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	Hwei: { key: "Hwei", name: "Hwei", primaryLane: Lane.Mid },
	Illaoi: { key: "Illaoi", name: "Illaoi", primaryLane: Lane.Top },
	Irelia: {
		key: "Irelia",
		name: "Irelia",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	Ivern: { key: "Ivern", name: "Ivern", primaryLane: Lane.Jungle },
	Janna: { key: "Janna", name: "Janna", primaryLane: Lane.Support },
	JarvanIV: { key: "JarvanIV", name: "Jarvan IV", primaryLane: Lane.Jungle },
	Jax: {
		key: "Jax",
		name: "Jax",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Jungle,
	},
	Jayce: {
		key: "Jayce",
		name: "Jayce",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Mid,
	},
	Jhin: { key: "Jhin", name: "Jhin", primaryLane: Lane.ADC },
	Jinx: { key: "Jinx", name: "Jinx", primaryLane: Lane.ADC },
	KSante: { key: "KSante", name: "K'Sante", primaryLane: Lane.Top },
	Kaisa: { key: "Kaisa", name: "Kai'Sa", primaryLane: Lane.ADC },
	Kalista: { key: "Kalista", name: "Kalista", primaryLane: Lane.ADC },
	Karma: {
		key: "Karma",
		name: "Karma",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	Karthus: {
		key: "Karthus",
		name: "Karthus",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	Kassadin: { key: "Kassadin", name: "Kassadin", primaryLane: Lane.Mid },
	Katarina: { key: "Katarina", name: "Katarina", primaryLane: Lane.Mid },
	Kayle: { key: "Kayle", name: "Kayle", primaryLane: Lane.Top },
	Kayn: { key: "Kayn", name: "Kayn", primaryLane: Lane.Jungle },
	Kennen: { key: "Kennen", name: "Kennen", primaryLane: Lane.Top },
	Khazix: { key: "Khazix", name: "Kha'Zix", primaryLane: Lane.Jungle },
	Kindred: { key: "Kindred", name: "Kindred", primaryLane: Lane.Jungle },
	Kled: { key: "Kled", name: "Kled", primaryLane: Lane.Top },
	KogMaw: { key: "KogMaw", name: "Kog'Maw", primaryLane: Lane.ADC },
	Leblanc: { key: "Leblanc", name: "LeBlanc", primaryLane: Lane.Mid },
	LeeSin: { key: "LeeSin", name: "Lee Sin", primaryLane: Lane.Jungle },
	Leona: { key: "Leona", name: "Leona", primaryLane: Lane.Support },
	Lillia: { key: "Lillia", name: "Lillia", primaryLane: Lane.Jungle },
	Lissandra: { key: "Lissandra", name: "Lissandra", primaryLane: Lane.Mid },
	Lucian: {
		key: "Lucian",
		name: "Lucian",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	Lulu: { key: "Lulu", name: "Lulu", primaryLane: Lane.Support },
	Lux: {
		key: "Lux",
		name: "Lux",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	Malphite: {
		key: "Malphite",
		name: "Malphite",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	Malzahar: { key: "Malzahar", name: "Malzahar", primaryLane: Lane.Mid },
	Maokai: {
		key: "Maokai",
		name: "Maokai",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Jungle,
	},
	MasterYi: { key: "MasterYi", name: "Master Yi", primaryLane: Lane.Jungle },
	Mel: { key: "Mel", name: "Mel", primaryLane: Lane.Mid },
	Milio: { key: "Milio", name: "Milio", primaryLane: Lane.Support },
	MissFortune: {
		key: "MissFortune",
		name: "Miss Fortune",
		primaryLane: Lane.ADC,
	},
	Mordekaiser: {
		key: "Mordekaiser",
		name: "Mordekaiser",
		primaryLane: Lane.Top,
	},
	Morgana: {
		key: "Morgana",
		name: "Morgana",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	Naafiri: { key: "Naafiri", name: "Naafiri", primaryLane: Lane.Mid },
	Nami: { key: "Nami", name: "Nami", primaryLane: Lane.Support },
	Nasus: { key: "Nasus", name: "Nasus", primaryLane: Lane.Top },
	Nautilus: { key: "Nautilus", name: "Nautilus", primaryLane: Lane.Support },
	Neeko: {
		key: "Neeko",
		name: "Neeko",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	Nidalee: { key: "Nidalee", name: "Nidalee", primaryLane: Lane.Jungle },
	Nilah: { key: "Nilah", name: "Nilah", primaryLane: Lane.ADC },
	Nocturne: { key: "Nocturne", name: "Nocturne", primaryLane: Lane.Jungle },
	Nunu: { key: "Nunu", name: "Nunu & Willump", primaryLane: Lane.Jungle },
	Olaf: {
		key: "Olaf",
		name: "Olaf",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	Orianna: { key: "Orianna", name: "Orianna", primaryLane: Lane.Mid },
	Ornn: { key: "Ornn", name: "Ornn", primaryLane: Lane.Top },
	Pantheon: {
		key: "Pantheon",
		name: "Pantheon",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Top,
	},
	Poppy: {
		key: "Poppy",
		name: "Poppy",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	Pyke: { key: "Pyke", name: "Pyke", primaryLane: Lane.Support },
	Qiyana: { key: "Qiyana", name: "Qiyana", primaryLane: Lane.Mid },
	Quinn: { key: "Quinn", name: "Quinn", primaryLane: Lane.Top },
	Rammus: { key: "Rammus", name: "Rammus", primaryLane: Lane.Jungle },
	RekSai: { key: "RekSai", name: "Rek'Sai", primaryLane: Lane.Jungle },
	Rell: { key: "Rell", name: "Rell", primaryLane: Lane.Support },
	Renata: { key: "Renata", name: "Renata Glasc", primaryLane: Lane.Support },
	Renekton: { key: "Renekton", name: "Renekton", primaryLane: Lane.Top },
	Rengar: {
		key: "Rengar",
		name: "Rengar",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	Riven: { key: "Riven", name: "Riven", primaryLane: Lane.Top },
	Rumble: { key: "Rumble", name: "Rumble", primaryLane: Lane.Top },
	Ryze: { key: "Ryze", name: "Ryze", primaryLane: Lane.Mid },
	Samira: { key: "Samira", name: "Samira", primaryLane: Lane.ADC },
	Sejuani: { key: "Sejuani", name: "Sejuani", primaryLane: Lane.Jungle },
	Senna: {
		key: "Senna",
		name: "Senna",
		primaryLane: Lane.Support,
		secondaryLane: Lane.ADC,
	},
	Seraphine: {
		key: "Seraphine",
		name: "Seraphine",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	Sett: { key: "Sett", name: "Sett", primaryLane: Lane.Top },
	Shaco: { key: "Shaco", name: "Shaco", primaryLane: Lane.Jungle },
	Shen: {
		key: "Shen",
		name: "Shen",
		primaryLane: Lane.Top,
		secondaryLane: Lane.Support,
	},
	Shyvana: { key: "Shyvana", name: "Shyvana", primaryLane: Lane.Jungle },
	Singed: { key: "Singed", name: "Singed", primaryLane: Lane.Top },
	Sion: { key: "Sion", name: "Sion", primaryLane: Lane.Top },
	Sivir: { key: "Sivir", name: "Sivir", primaryLane: Lane.ADC },
	Skarner: {
		key: "Skarner",
		name: "Skarner",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	Smolder: { key: "Smolder", name: "Smolder", primaryLane: Lane.ADC },
	Sona: { key: "Sona", name: "Sona", primaryLane: Lane.Support },
	Soraka: { key: "Soraka", name: "Soraka", primaryLane: Lane.Support },
	Swain: {
		key: "Swain",
		name: "Swain",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	Sylas: { key: "Sylas", name: "Sylas", primaryLane: Lane.Mid },
	Syndra: { key: "Syndra", name: "Syndra", primaryLane: Lane.Mid },
	TahmKench: {
		key: "TahmKench",
		name: "Tahm Kench",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Top,
	},
	Taliyah: {
		key: "Taliyah",
		name: "Taliyah",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	Talon: {
		key: "Talon",
		name: "Talon",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Mid,
	},
	Taric: { key: "Taric", name: "Taric", primaryLane: Lane.Support },
	Teemo: { key: "Teemo", name: "Teemo", primaryLane: Lane.Top },
	Thresh: { key: "Thresh", name: "Thresh", primaryLane: Lane.Support },
	Tristana: { key: "Tristana", name: "Tristana", primaryLane: Lane.ADC },
	Trundle: {
		key: "Trundle",
		name: "Trundle",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	Tryndamere: { key: "Tryndamere", name: "Tryndamere", primaryLane: Lane.Top },
	TwistedFate: {
		key: "TwistedFate",
		name: "Twisted Fate",
		primaryLane: Lane.Mid,
	},
	Twitch: {
		key: "Twitch",
		name: "Twitch",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Jungle,
	},
	Udyr: { key: "Udyr", name: "Udyr", primaryLane: Lane.Jungle },
	Urgot: { key: "Urgot", name: "Urgot", primaryLane: Lane.Top },
	Varus: {
		key: "Varus",
		name: "Varus",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	Vayne: { key: "Vayne", name: "Vayne", primaryLane: Lane.ADC },
	Veigar: {
		key: "Veigar",
		name: "Veigar",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Support,
	},
	Velkoz: {
		key: "Velkoz",
		name: "Vel'Koz",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	Vex: { key: "Vex", name: "Vex", primaryLane: Lane.Mid },
	Vi: { key: "Vi", name: "Vi", primaryLane: Lane.Jungle },
	Viego: { key: "Viego", name: "Viego", primaryLane: Lane.Jungle },
	Viktor: { key: "Viktor", name: "Viktor", primaryLane: Lane.Mid },
	Vladimir: {
		key: "Vladimir",
		name: "Vladimir",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	Volibear: {
		key: "Volibear",
		name: "Volibear",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	Warwick: { key: "Warwick", name: "Warwick", primaryLane: Lane.Jungle },
	MonkeyKing: {
		key: "MonkeyKing",
		name: "Wukong",
		primaryLane: Lane.Jungle,
		secondaryLane: Lane.Top,
	},
	Xayah: { key: "Xayah", name: "Xayah", primaryLane: Lane.ADC },
	Xerath: {
		key: "Xerath",
		name: "Xerath",
		primaryLane: Lane.Support,
		secondaryLane: Lane.Mid,
	},
	XinZhao: { key: "XinZhao", name: "Xin Zhao", primaryLane: Lane.Jungle },
	Yasuo: {
		key: "Yasuo",
		name: "Yasuo",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.ADC,
	},
	Yone: {
		key: "Yone",
		name: "Yone",
		primaryLane: Lane.Mid,
		secondaryLane: Lane.Top,
	},
	Yorick: { key: "Yorick", name: "Yorick", primaryLane: Lane.Top },
	Yuumi: { key: "Yuumi", name: "Yuumi", primaryLane: Lane.Support },
	Zac: { key: "Zac", name: "Zac", primaryLane: Lane.Jungle },
	Zed: { key: "Zed", name: "Zed", primaryLane: Lane.Mid },
	Zeri: { key: "Zeri", name: "Zeri", primaryLane: Lane.ADC },
	Ziggs: {
		key: "Ziggs",
		name: "Ziggs",
		primaryLane: Lane.ADC,
		secondaryLane: Lane.Mid,
	},
	Zilean: { key: "Zilean", name: "Zilean", primaryLane: Lane.Support },
	Zoe: { key: "Zoe", name: "Zoe", primaryLane: Lane.Mid },
	Zyra: { key: "Zyra", name: "Zyra", primaryLane: Lane.Support },
};
